### ISSUE TITLE
Add English language

### ISSUE THREAD

**Issue by EgidioCaprino** [capcatit/capcatit.github.io#3]

**Comment by toncatalansuazo** [comment]
working in it

**Comment by toncatalansuazo** [comment]
@EgidioCaprino I tried to integrate next-i18next but if I tried to use the **next.config.js** [link-to-file](https://github.com/capcatit/capcat.github.io/blob/ad85cce167511af24adc1f58e233c18dc9bb9c1b/pages/index.js#L7) configuration in this way 
`const { t } = useTranslation('common', {useSuspense: false, {i18n }})`
I got an error `react doesnt found`

**Comment by EgidioCaprino** [comment]
Hey @toncatalansuazo, can you try importing `React` as first thing in your file?

```javascript
import React from 'react';
....
```

**Comment by toncatalansuazo** [comment]
I change library to **next-translate**
